'use strict';

enum ErrorType {
    DATABASE_ERROR = 'DATABASE ERROR',
    ORDER_SERVICE_ERROR = 'ORDER SERVICE ERROR',
    ORDER_DATA_CONFLICT = 'ORDER DATA CONFLICT',
    ORDER_INVALID_REQUEST = 'ORDER INVALID REQUEST',
    ORDER_UNAUTHORIZED = 'ORDER UNAUTHORIZE',
    FOUND_AT_THIS_URL = 'FOUND AT THIS URL',
    USER_UNAUTHORIZED = 'USER UNAUTHORIZE',
}

export default ErrorType;
